import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/layouts/footer";
import Header from "@/layouts/header";
import CustomBody from "@/components/custom-body";
import "animate.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <CustomBody>
        <Header />
        {children}
        <Footer />
      </CustomBody>
    </html>
  );
}
